name: checking
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: my-step_1
        run: flake8 .
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: my-step_2
        run: pytest
