name: checking
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: my-step_1
        run: echo "Hello Lint!"
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: my-step_2
        run: echo "Hello Test!"
