name: checking
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: my-step_0
        run: pip install poetry
      - name: my-step_1
        run: poetry install
      - name: my-step_2
        run: poetry run pytest
      - name: my-step_3
        run: poetry run flake8 gendiff
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make report
