name: checking
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: my-step_1
        run: poetry install
      - name: my-step_2
        run: poetry run flake8 gendiff
      - name: my-step_3
        run: poetry run pytest
